### ISSUE TITLE
"Load setup" adds multiple docks and toolbars

### ISSUE THREAD

**Issue by boogiedave** [jankae/LibreVNA#103]
Every time when I load a stored setup, gui objects (toolbars, docks...) from the loaded setup are added to the window.
The screenshot shows the gui after consecutively loading three setups.
![grafik](https://user-images.githubusercontent.com/104825543/168062768-99462759-2af7-4537-85b8-3300afd9ebe6.png)

System: Ubuntu 20.04.4 LTS (Xfce)

**Comment by jankae** [comment]
I assume you are using the 1.3.0 Release? If so, can you please try the latest development version? As far as I know, this has been fixed by cacea26e

**Comment by boogiedave** [comment]
You're right. Thanks. Also for this very useful piece of electronics!
