### ISSUE TITLE
Signal generator stepping frequency by mouse scroll wheel 

### ISSUE THREAD

**Issue by oz7ou** [jankae/LibreVNA#104]
I would be a nice feature it the frequency could be manually stepped by scrolling the mouse whell. The step size e.g. by selecting the mouse position on the frequency entry field or by a selection in a drop box.
Kind regards
Kurt

**Comment by jankae** [comment]
Hi Kurt,

> The step size e.g. by selecting the mouse position on the frequency entry field

It already works like that: click in the frequency field and position the cursor behind the digit you want to change. Then use the mouse wheel to change that digit. This works for every entry field that uses the internal SIUnitEdit class (which is almost every entry field throughout the GUI)

**Comment by oz7ou** [comment]
Hi Jan

Thank you very much for this excellent information. I did try so a couple of times and now I can trace why it did not worked so.

Kind regards 

Kurt

 

Fra: jankae ***@***.***> 
Sendt: 19. maj 2022 19:18
Til: jankae/LibreVNA ***@***.***>
Cc: oz7ou ***@***.***>; Author ***@***.***>
Emne: Re: [jankae/LibreVNA] Signal generator stepping frequency by mouse scroll wheel (Issue #104)

 

Hi Kurt,

The step size e.g. by selecting the mouse position on the frequency entry field

It already works like that: click in the frequency field and position the cursor behind the digit you want to change. Then use the mouse wheel to change that digit. This works for every entry field that uses the internal SIUnitEdit class (which is almost every entry field throughout the GUI)
