### ISSUE TITLE
Change color for default traces

### ISSUE THREAD

**Issue by lucasub** [jankae/LibreVNA#114]
I was unable to change the color of the tracks present by default, while adding a new one this is possible. I ask this because the S21 track is DARK BLUE and is not very visible on a black background. 
Thank you a lot

**Comment by sophiekovalevsky** [comment]
@lucasub thanks for reporting this. 

I can confirm this behavior by doing the following steps:

- Open LibreVNA app without attaching any device to it
- Open it Trace Edit Dialog and change it's color
- Color is updated on Traces Dock, however, it's not propagated until current opened plots. 

PR recently pushed fixes this.

**Comment by lucasub** [comment]
Ok, I try. It's work well. Thank you
