### ISSUE TITLE
Marker temporary hide

### ISSUE THREAD

**Issue by nbgsmk** [jankae/LibreVNA#128]
### Summary

I tend to have a lot of markers in my graphs. Sometimes handling them all becomes tedious and the screen becomes cluttered. Especially when using bandpass, combined to other 'characteristic' points of interest nearby.
It would be a great help to temporary hide any marker 'triangle' from the graph (similarly as the traces can be hidden). The textual data on the right is ok to remain.
For marker groups such as bandpass, it would be sufficient to hide the whole group at once (hide each separately is also ok, whichever is easier to implement)

### Paths to implement it

Excuse my poor copy-pasting in paint, but something like this:

![image](https://user-images.githubusercontent.com/60575976/178060025-80a807ae-9982-4e05-af2f-c5c8c56f6c63.png)

### Extra information

n/a

**Comment by jankae** [comment]
Done, see 2954406
![image](https://user-images.githubusercontent.com/16818866/178105917-2f63cc51-d281-4833-bffd-98b2c6805bf6.png)

**Comment by nbgsmk** [comment]
Great, I love it! Works like a charm. Closing.
