### ISSUE TITLE
Smith Chart Displays

### ISSUE THREAD

**Issue by YuryW** [jankae/LibreVNA#132]
### LibreVNA Version

![image](https://user-images.githubusercontent.com/79474615/178118211-935935fb-5320-4e51-aeba-def2faa49c5e.png)

### Steps to reproduce

The LibreVNA application is running. The LibreVNA device is not connected.

### Expected behavior

Not all input parameters can be loaded into Smith charts for s3p and s4p files, in this case the S22 imported file. Or am I doing something wrong?
![Import_trases - копия](https://user-images.githubusercontent.com/79474615/178118414-9afd116d-2524-4346-8c7f-5417849ed35c.jpg)
![Import_trases_1 - копия](https://user-images.githubusercontent.com/79474615/178118425-0d7f12f4-b0ea-4c5a-9fda-ea359b2af50a.jpg)
And can you make it so that the extensions of imported third-party sXp files would be case-insensitive, since S3P (S4P) files often come across and the program now swears at them?

### Extra information & Setup and Calibration files

[TCM1-83X+_S3P.zip](https://github.com/jankae/LibreVNA/files/9077694/TCM1-83X%2B_S3P.zip)

### Confirming that you haven´t forgot to include configuration files (if applicable)

- [ ] Setup file
- [ ] Calibration file
- [X] Touchstone file of measurements

**Comment by jankae** [comment]
For now, you can only add reflection measurements to a smith chart. In your example, S22 **is** a reflection measurement and should work.
However, there was an error in the code that determines whether a trace is a reflection measurement when the imported touchstone file has more than two ports. That is why you can instead add S21, which should not be possible.
I just fixed this (3af9b73), it now works as expected.

**Comment by jankae** [comment]
> And can you make it so that the extensions of imported third-party sXp files would be case-insensitive, since S3P (S4P) files often come across and the program now swears at them?

Almost forgot about that one. Importing .S3P is now also possible without an error message.

**Comment by YuryW** [comment]
Simply amazing! So quickly fixed! Best regards.
We close the question.

**Comment by jankae** [comment]
Happy to help :)
