### ISSUE TITLE
GUI V1.4.0 Won't Start 

### ISSUE THREAD

**Issue by dsbrantjr** [jankae/LibreVNA#140]
### LibreVNA Version

1.4.0 latest release, can't get app info 'cause it won't start
Same behavior with 1.3.0 and 1.4.0 firmwares

### Steps to reproduce

1-  double-click LibreVNA-GUI.exe
2-  Result:  ![Capture](https://user-images.githubusercontent.com/72746886/180670745-cef1fc65-b1ee-44b9-b5b6-83e3428b8576.GIF)

Behavior persists after restart and after re-download win 10 Pro 21H2 32GB RAM
1.3.0 GUI works. I used it to update firmware to 1.4.0

### Expected behavior

I expect GUI to start and run

### Extra information & Setup and Calibration files

None

### Confirming that you haven´t forgot to include configuration files (if applicable)

- [X] Setup file
- [X] Calibration file
- [X] Touchstone file of measurements

**Comment by jankae** [comment]
The compiler setup for the release version was still broken (I fixed this a while ago for the CI toolchain in the development versions but forgot to adjust the release toolchain as well). I manually replaced the binary now, please download it again.
