### ISSUE TITLE
Delayed reaction of the Smith chart pop-up submenu to changes in the reference resistance of this chart.

### ISSUE THREAD

**Issue by YuryW** [jankae/LibreVNA#141]
### LibreVNA Version

LibreVNA Version (64 bit): 1.4.0-7f6b78992
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU Arch: x86_64

### Steps to reproduce

LibreVNA application launched.
LibreVNA device is not connected.

### Expected behavior

The Smith chart should always display only touchstone files with the same reference impedances.

We have 2 touchstone files Test_R_75.s2p and Test_R_50.s2p, differing only in reference resistance. In Test_R_75.s2p it is 75 ohms:
![image](https://user-images.githubusercontent.com/79474615/181497063-0cfe90a4-ca8c-4e86-9c82-97b4a9e3fdc2.png) and in Test_R_50.s2p it is 50 Ohm:
![image](https://user-images.githubusercontent.com/79474615/181497255-f426a302-c382-4af9-87e7-3b3bd351733f.png).
Import both files into LibreVNA v1.4.0. 
![image](https://user-images.githubusercontent.com/79474615/181496781-f7880ee7-8d7b-41fb-b90e-eba3bb157086.png)
The floating submenu on the Smith chart contains only those files whose reference impedance matches the reference impedance of the Smith chart. The default is 50 ohms.
You can change the Smith chart reference impedance in the Setup settings of this pop-up submenu, only in this case by unchecking the S11 LibreVNA characteristic:
![image](https://user-images.githubusercontent.com/79474615/181497463-735dc65f-e44e-40d6-bce6-f51a8466368b.png)
Let's do this and set the reference impedance to 75 ohms:
![image](https://user-images.githubusercontent.com/79474615/181497723-26fb4792-2c49-4e86-a980-df7557c851c9.png)
We click OK and (surprisingly) all the same, in the pop-up submenu it is proposed to display touchstone files with a reference resistance of 50 Ohms, and not 75 Ohms, on the Smith chart.
![image](https://user-images.githubusercontent.com/79474615/181498007-9dc2ad5f-2413-4922-b506-0c1d3b06065d.png)
Check the box next to Test_R_50_S11 (with a reference impedance of 50 ohms) and this file is displayed on the Smith chart with a reference impedance of 75 ohms. And only after that (after adding the first file to the Smith chart) in the pop-up submenu, files with a reference resistance of 75 Ohm are offered as needed:
![image](https://user-images.githubusercontent.com/79474615/181498266-a7d64b83-f13a-4068-9534-1bd3846956e0.png)
Put a tick in front of Test_R_75_S11 and get:
![image](https://user-images.githubusercontent.com/79474615/181498546-26b0c0d7-388b-4264-883d-4d0d5cf7b9ee.png)
The result on the Smith chart with a reference resistance of 75 ohms, files with a reference resistance of 50 ohms and 75 ohms were loaded at the same time, which, probably, was not expected:
![image](https://user-images.githubusercontent.com/79474615/181498645-791eab16-b57d-4938-848a-2d16ca4374ce.png)
As a result, this situation is possible due to the fact that after changing the reference impedance in the Setup settings of the pop-up submenu, before the first transfer of the touchstone file to the Smith Chart, the pop-up submenu offers to load the previous version with the previous reference impedance.

 

 

### Extra information & Setup and Calibration files

[Test_R_75.s2p_Test_R_50.s2p.zip](https://github.com/jankae/LibreVNA/files/9209136/Test_R_75.s2p_Test_R_50.s2p.zip)

### Confirming that you haven´t forgot to include configuration files (if applicable)

- [ ] Setup file
- [ ] Calibration file
- [X] Touchstone file of measurements

**Comment by jankae** [comment]
Thank you for the excellent bug report. The context menu (pop-up) wasn't updated properly when changing settings of the smith chart (e.g. the reference impedance). 6a27d39 should fix that.

**Comment by YuryW** [comment]
Thanks for the quick response and fixes as always. We close the question.
Best regards!
