### ISSUE TITLE
Documentation - Programming  Guide

### ISSUE THREAD

**Issue by Hanier** [jankae/LibreVNA#149]
### LibreVNA Version

LibreVNA SCPI Programming Guide
June 26, 2022

### Steps to reproduce

On pages 9&10 in the manual, the following commands are missing the :LIMit: portion of the statement in the syntax description.  The format needed may be seen using the '*LST?' query.     The *LST? query shows the correct syntax.

    print("Min Frequency: %s" % (vna.query(":DEV:INF:LIM:MINF?")) )
    print("Max Frequency: %s" % (vna.query(":DEV:INF:LIM:MAXF?")) )
    print("Min IFBW: %s" % (vna.query(":DEV:INF:LIM:MINIFBW?")) )
    print("Max IFBW: %s" % (vna.query(":DEV:INF:LIM:MAXIFBW?")) )
    print("Max Points: %s" % (vna.query(":DEV:INF:LIM:MAXP?")) )
    print("Min Power: %s" % (vna.query(":DEV:INF:LIM:MINPOW?")) )
    print("Max Power: %s" % (vna.query(":DEV:INF:LIM:MAXPOW?")) )
    print("Min RBW: %s" % (vna.query(":DEV:INF:LIM:MINRBW?")) )
    print("Max RBW: %s" % (vna.query(":DEV:INF:LIM:MAXRBW?")) )
    print("Max Harmonic Frequency: %s" % (vna.query(":DEV:INF:LIM:MAXHARM?")) )

### Expected behavior

Syntax from the manual results in a return value  = ERROR

### Extra information & Setup and Calibration files

NONE

### Confirming that you haven´t forgot to include configuration files (if applicable)

- [ ] Setup file
- [ ] Calibration file
- [ ] Touchstone file of measurements

**Comment by jankae** [comment]
Thank you for the issue, as you figured out yourself this is obviously an error in the programming guide. I have fixed this now
