### ISSUE TITLE
Application LibreVNA Version (64 bit): 1.5.0-alpha.1-c7a99af82 expands to full screen on the third try.

### ISSUE THREAD

**Issue by YuryW** [jankae/LibreVNA#154]
### LibreVNA Version

LibreVNA Version (64 bit): 1.5.0-alpha.1-c7a99af82
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU Arch: x86_64

### Steps to reproduce

Only the LibreVNA application is running. The device is not connected. Monitor screen resolution 3840x2160.
After launching the application, it is first located in the upper left corner. After clicking the mouse on a full screen scan, it moves a little lower and to the right. And only after the next mouse click on the full screen scan, everything turns out.
![1 - копия](https://user-images.githubusercontent.com/79474615/197277427-cd035287-f389-4745-b6de-fd502e26ad96.jpg)
![2 - копия](https://user-images.githubusercontent.com/79474615/197277477-5db2480c-5ad5-41bd-935c-9674cd18edca.jpg)
![3 - копия](https://user-images.githubusercontent.com/79474615/197277577-34887feb-af76-4c47-b109-b17f4c52d16b.jpg)
When hovering the mouse in the upper right corner of the application screen, instead of Maximize window, "Minimize to window" is displayed, although it is already in this state. When you repeat the procedure with the window shifted below, the inscription "Expand" already appears and then everything works normally. The "problem" is solved if you expand the window to full screen with the mouse by moving the application up behind the monitor screen.

### Expected behavior

For version: 
LibreVNA Version (64 bit): 1.4.0-7f6b78992
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU Arch: x86_64
The application immediately expanded to full screen.
Perhaps I missed something?

### Extra information & Setup and Calibration files

No.

### Confirming that you haven´t forgot to include configuration files (if applicable)

- [ ] Setup file
- [ ] Calibration file
- [ ] Touchstone file of measurements

**Comment by YuryW** [comment]
Tried Default values, Last used, Setup file. All the same. Okay, it's not that hard to double click the mouse. Perhaps, over time, it will be decided or no one will use W7. ))

**Comment by YuryW** [comment]
LibreVNA Version (64 bit): 1.5.0-alpha.1-796a8cb3f
OS: Windows 10 21H2 Version 19044.1288
CPU Arch: x86_64
For Windows 10 and with a screen resolution of 3840x2160, the same pattern repeats as in the first question.

For all subsequent commits, up to today, when you try to run the LibreVNA_GUI application on Win7 or Win10, the following splash screen appears.

LibreVNA-GUI.exe - System error. 
 Unable to continue code execution because the system has not detected libusb-1.0.dll . To fix this problem, try reinstalling the program.

**Comment by dna35** [comment]
I noticed the same 3 time click operation but have ignored it until seeing this post.

LibreVNA Version (64 bit): 1.5.0-alpha.2-b67275831
OS: Windows 10 Version 2009
CPU Arch: x86_64

Display #2 or far left of three displays sometimes goes off screen on the right side and can't see the bottom parts of the GUI unless not in max window size. I'm using DualMonitor tools but unknown if it is related. However, don't know when it will do it yet.

**Comment by jankae** [comment]
If I can replicate this myself I would attempt to fix it. But I haven't ever seen this, so I am unlikely to find the problem.
I'll go ahead and close this for now. If you (or anyone else) has new information about this, I'll happily reopen this.
