### ISSUE TITLE
Parameters for PCB manufacturing + gerbers

### ISSUE THREAD

**Issue by WojtaCZ** [jankae/LibreVNA#162]
### Summary

Could you please provide some parameters that the PCB should be manufactured with plus gerbers generated from the eagle project?

### Paths to implement it

Usefull parameters:
- Stackup, either table with necessary values or manufacturer and their standard
- Special requirements (blind vias, POVF vias etc.)
- Basic parameters (pcb size, number of layers...)

Exported gerbers ready for manufacturing for those who don't work with eagle.

### Extra information

 I guess the parameters can be found out from the eagle project but it still would be nice to have them listed somewhere for non Eagle users.

**Comment by jankae** [comment]
Sure, I have added the required files here: https://github.com/jankae/LibreVNA/tree/master/Hardware/Gerber

> Stackup, either table with necessary values or manufacturer and their standard

Screenshot from Eagle DRC is included.

> Special requirements (blind vias, POVF vias etc.)

Nothing special, just normal through hole vias. I am not sure what you mean by POVF vias.

**Comment by WojtaCZ** [comment]
Perfect, thank you very much :)
