### ISSUE TITLE
Keep original trace data when de-embedding

### ISSUE THREAD

**Issue by YuryW** [jankae/LibreVNA#171]
### LibreVNA Version

LibreVNA Version (64 bit): 1.5.0-alpha.2-89c9f20d1
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU Arch: x86_64

### Steps to reproduce

Only the LibreVNA application is running.
Imported s3p file. When de-embedding, s2p shunts are inserted in all three ports. After pressing OK in Select Color, the color of the trace changes. After pressing OK in the Edit Trace menu, the trace changes with the changed color (not saved).
![Color](https://user-images.githubusercontent.com/79474615/206929335-e8333779-68bd-4245-9b85-146d50ea81c5.jpg)

![Color_1](https://user-images.githubusercontent.com/79474615/206929351-59bbde2d-0182-4d20-8707-50ff5da43cdd.jpg)

![Color_2](https://user-images.githubusercontent.com/79474615/206929361-4f494496-b364-4cfc-bedf-9817075789bd.jpg)

![Color_3](https://user-images.githubusercontent.com/79474615/206929376-1cee4d2a-afb8-4d59-bfea-64f661fb344c.jpg)

### Expected behavior

When changing colors on de-embedding tracks, only the color changes, and the result of em-bedding should be saved.

### Extra information & Setup and Calibration files

[sNp.zip](https://github.com/jankae/LibreVNA/files/10203322/sNp.zip)

**Comment by jankae** [comment]
The issue wasn't the color change itself but rather the trace edit dialog: whenever the dialog is closed by pressing OK, the trace data was reloaded from the file. This implicitly caused the de-embedding data to be deleted.
[Fix:](https://github.com/jankae/LibreVNA/commit/fa8f49086cd6b56329502e9653327923f689f975) only reload the trace from file when the filename actually has changed.
