### ISSUE TITLE
Adding support for 4" NanoVNA

### ISSUE THREAD

**Issue by kooscode** [jankae/LibreVNA#184]
### Summary

Can you please add support for this hardware ID:

lsbusb reports: 

**0483:5740 STMicroelectronics Virtual COM Port**

### Paths to implement it

https://github.com/jankae/LibreVNA/blob/master/Software/PC_Application/LibreVNA-GUI/Device/device.cpp#L18

```
static constexpr USBID IDs[] = {
    {0x0483, 0x564e},
    {0x0483, 0x4121},
    {0x0483, 0x5740},
};
```

### Extra information

For this device:
https://www.amazon.com/dp/B083PQ4RXZ

**Comment by jankae** [comment]
The NanoVNA is a different project with a different USB protocol. Simply adding the VID/PID will not make it work with the LibreVNA-GUI. You are free to add support for the NanoVNA yourself and I will merge that but I will not add that myself.
