### ISSUE TITLE
SG Calibration Routine

### ISSUE THREAD

**Issue by dna35** [jankae/LibreVNA#188]
### Summary

LibreVNA Version (64 bit): 1.5.0-alpha.2-3d51f1f49
OS: Windows 10 Version 2009
CPU Arch: x86_64

Considering the prevalence of two LibreVna's used as SG's for common measurements, developing a calibration routine for the output magnitude would be nice regardless of phasing.

![25MHz verification waveform](https://user-images.githubusercontent.com/36786668/209735330-b3fd7cd1-821a-4677-87bc-25b3d6a26e9a.png)
Fig. 1 VNA1 to both inputs of PicoScope with a reasonable amplitude match

![VNA1 Blue VNA2 Red -10dBm Port 1 difference](https://user-images.githubusercontent.com/36786668/209735417-2a1e0de8-acc3-4e19-abd0-7ed853824bb5.png)
Fig. 2 VNA1 & VNA2 Magnitude mismatch of ~ 10mV Pk to Pk without considering the phase missmatch

### Paths to implement it

Calibration routine based on a known dBm level.

### Extra information

None

**Comment by jankae** [comment]
This already exists - see section 9.1 in the user manual (Source Calibration)

**Comment by dna35** [comment]
Hmm, I'm using the same source calibration. therfore, it must need to be instrument specific.
So just to confirm, that means three different source calibrations.

1- Source Cal VNA1
2- Source Cal VNA2
3- Source Cal VNA1&2

**Comment by jankae** [comment]
No, the is one source calibration per physical device. It is stored on the LibreVNA itself. But of course there are differences between samples.

So you need:
VNA1: Source calibration 1
VNA2: Source calibration 2
VNA1&2: nothing special needs to be done, they both use their respective source calibration (if one is available)

**Comment by dna35** [comment]
Thanks Jan, I'm working on the Source calibrations and will close this as already implemented.
