### ISSUE TITLE
NanoVNA not recognized under  Linux Ubuntu & LibreVNA GUI 1.2.1

### ISSUE THREAD

**Issue by zolfist** [jankae/LibreVNA#193]
### LibreVNA Version

NanoVNA not recognized under Ubuntu 22.04.1 LTS 64bit

Tested LibreVNA GUI 1.2.1

### Steps to reproduce

dmesg shows:

[ 1038.200220] usb 1-3: New USB device found, idVendor=0483, idProduct=5740, bcdDevice= 2.00
[ 1038.200238] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1038.200245] usb 1-3: Product: ChibiOS/RT Virtual COM Port
[ 1038.200250] usb 1-3: Manufacturer: STMicroelectronics
[ 1038.200255] usb 1-3: SerialNumber: 400
[ 1038.202563] cdc_acm 1-3:1.0: ttyACM0: USB ACM device

but LibreVNA GUI shows no device after Update Device list

     0.138: [debug] Application start
     0.143: [info] Loading preferences
     0.143: [debug] Setting "Startup.ConnectToFirstDevice" is set to QVariant(bool, true)
     0.143: [debug] Setting "Startup.RememberSweepSettings" is set to QVariant(bool, false)
     0.143: [debug] Setting "Startup.DefaultSweep.type" is set to QVariant(QString, "Frequency")
     0.143: [debug] Setting "Startup.DefaultSweep.start" is set to QVariant(double, 1e+06)
     0.143: [debug] Setting "Startup.DefaultSweep.stop" is set to QVariant(double, 6e+09)
     0.143: [debug] Setting "Startup.DefaultSweep.excitation" is set to QVariant(double, -10)
     0.143: [debug] Setting "Startup.DefaultSweep.dbm_start" is set to QVariant(double, -30)
     0.143: [debug] Setting "Startup.DefaultSweep.dbm_stop" is set to QVariant(double, -10)
     0.143: [debug] Setting "Startup.DefaultSweep.dbm_freq" is set to QVariant(double, 1e+09)
     0.143: [debug] Setting "Startup.DefaultSweep.points" is set to QVariant(int, 501)
     0.143: [debug] Setting "Startup.DefaultSweep.bandwidth" is set to QVariant(double, 1000)
     0.143: [debug] Setting "Startup.DefaultSweep.averaging" is set to QVariant(int, 1)
     0.143: [debug] Setting "Startup.Generator.frequency" is set to QVariant(double, 1e+09)
     0.143: [debug] Setting "Startup.Generator.level" is set to QVariant(double, -10)
     0.143: [debug] Setting "Startup.SA.start" is set to QVariant(double, 9.5e+08)
     0.143: [debug] Setting "Startup.SA.stop" is set to QVariant(double, 1.05e+09)
     0.143: [debug] Setting "Startup.SA.RBW" is set to QVariant(double, 10000)
     0.143: [debug] Setting "Startup.SA.window" is set to QVariant(int, 1)
     0.143: [debug] Setting "Startup.SA.detector" is set to QVariant(int, 0)
     0.143: [debug] Setting "Startup.SA.averaging" is set to QVariant(int, 1)
     0.143: [debug] Setting "Startup.SA.signalID" is set to QVariant(bool, true)
     0.143: [debug] Setting "Acquisition.alwaysExciteBothPorts" is set to QVariant(bool, true)
     0.143: [debug] Setting "Acquisition.suppressPeaks" is set to QVariant(bool, true)
     0.143: [debug] Setting "Acquisition.adjustPowerLevel" is set to QVariant(bool, false)
     0.143: [debug] Setting "Acquisition.harmonicMixing" is set to QVariant(bool, false)
     0.143: [debug] Setting "Acquisition.useDFTinSAmode" is set to QVariant(bool, true)
     0.143: [debug] Setting "Acquisition.RBWLimitForDFT" is set to QVariant(double, 3000)
     0.143: [debug] Setting "Acquisition.useMedianAveraging" is set to QVariant(bool, false)
     0.143: [debug] Setting "Graphs.Color.background" is set to QVariant(QColor, QColor(ARGB 1, 0, 0, 0))
     0.143: [debug] Setting "Graphs.Color.axis" is set to QVariant(QColor, QColor(ARGB 1, 1, 1, 1))
     0.143: [debug] Setting "Graphs.Color.Ticks.Background.enabled" is set to QVariant(bool, true)
     0.143: [debug] Setting "Graphs.Color.Ticks.Background.background" is set to QVariant(QColor, QColor(ARGB 1, 0.0784314, 0.0784314, 0.0784314))
     0.143: [debug] Setting "Graphs.Color.Ticks.divisions" is set to QVariant(QColor, QColor(ARGB 1, 0.627451, 0.627451, 0.643137))
     0.143: [debug] Setting "Graphs.domainChangeBehavior" is set to QVariant(int, 1)
     0.143: [debug] Setting "Graphs.markerBehavior.ShowDataOnGraphs" is set to QVariant(bool, true)
     0.143: [debug] Setting "Graphs.markerBehavior.ShowAllData" is set to QVariant(bool, false)
     0.143: [debug] Setting "Graphs.lineWidth" is set to QVariant(double, 1)
     0.143: [debug] Setting "SCPIServer.enabled" is set to QVariant(bool, true)
     0.143: [debug] Setting "SCPIServer.port" is set to QVariant(int, 19542)
     0.143: [info] Listening on port 19542
     0.160: [debug] Activating mode "Vector Network Analyzer"
     0.163: [debug] Updated device list, found 0

 

### Expected behavior

usb-c device must be detected 

### Extra information & Setup and Calibration files

all are defaults

**Comment by jankae** [comment]
First of all, version 1.2.1 is rather old, you should always test with the latest version.

But in this case, it wouldn't help. This is the repository for the LibreVNA, a totally different project and not at all related to the NanoVNA.
