### ISSUE TITLE
Inaccuracies in transfer characteristics graphs at very small Primary Y axis divisions.

### ISSUE THREAD

**Issue by YuryW** [jankae/LibreVNA#206]
### LibreVNA Version

LibreVNA Version (64 bit): 1.5.0-alpha.2-7ebb1ea0c
OS: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU Arch: x86_64

### Steps to reproduce

LibreVNA application is running, LibreVNA device is running or not.
At very small divisions of the primary Y-axis, their display occurs with errors.
![Calibration_01dB](https://user-images.githubusercontent.com/79474615/228635410-ce3e3522-9b12-401b-bf13-369abc2cb6e2.jpg)
![Calibration_015dB](https://user-images.githubusercontent.com/79474615/228635477-7d2bcb96-2dfc-4152-a82f-3d67cae0a68c.jpg)

### Expected behavior

I expect correct display of small divisions of the primary Y-axis up to a step of 0.01dB (0.015dB).
And divisions of the main Y-axis, which cannot be adequately displayed by the application, could not be manually entered in the program settings.

### Extra information & Setup and Calibration files

No.

**Comment by jankae** [comment]
Huh, this was a floating point issue. 0.01 is actually stored as 0.009999...
This would normally not be a problem, the string conversion function does round the value. But my own function does some preprocessing to determine the prefix (if any should be used) and the number of displayed digits. In this case, the number of displayed digits (or precision) was determined to be 2 (leading zero does not count). 0.009999.. has just zeros for these two displayed digits, which resulted in abbreviating the whole thing as 0.
I have changed the calculation and take into account the remaining digits now as well to determine whether the value will be rounded up. Now the correct values show up:
![grafik](https://user-images.githubusercontent.com/16818866/230126694-fc0c7735-f3d5-427a-855c-2b9674e76a28.png)

**Comment by jankae** [comment]
Closing, as I believe this to be solved. Please reopen if you find any further issues related to this.

**Comment by YuryW** [comment]
Hi and thanks, Jankae.
Unfortunately, I was temporarily unable to check the new edition, since I mainly work on W7_64, and it does not support Qt6.
Best regards.
