### ISSUE TITLE
Spikes at 31MHz and 62MHz

### ISSUE THREAD

**Issue by Dmitrii1978** [jankae/LibreVNA#215]
### LibreVNA Version

LibreVNA Version (64 bit): 1.5.0-alpha.2-
OS: Windows 11 Version 22H2
CPU Arch: x86_64

### Steps to reproduce

Spikes at 31MHz and 62MHz and higher multiples frequencies.
![spikes](https://github.com/jankae/LibreVNA/assets/144907683/53275478-c893-4f91-8dc1-e5693dfcde89)

### Expected behavior

Is it possible to decrease level of these spikes?

### Extra information & Setup and Calibration files

The frequency range is set to 1MHz..101MHz , 4501 points, IF BW 1.00kHz

**Comment by jankae** [comment]
These spikes are caused by LO feedthrough (and mixing products of the two LOs). I don't think it is possible to remove them without drastic changes to the hardware, sorry.
You have the option to shift them to slightly different frequencies by changing the LO frequencies: Device->Configuration
![grafik](https://github.com/jankae/LibreVNA/assets/16818866/9b96707f-3b93-4bad-a215-70df1e434d9e)

This could be useful if you need to look at the actual signal right at these frequencies. But I would recommend changing the LO only by 1-2 MHz, otherwise the hardware filters may attenuate the signal too much (increased noise).

**Comment by YuryW** [comment]
> ### LibreVNA Version
> LibreVNA Version (64 bit): 1.5.0-alpha.2- OS: Windows 11 Version 22H2 CPU Arch: x86_64
> 
> ### Steps to reproduce
> Spikes at 31MHz and 62MHz and higher multiples frequencies. ![spikes](https://user-images.githubusercontent.com/144907683/267636375-53275478-c893-4f91-8dc1-e5693dfcde89.png)
> 
> ### Expected behavior
> Is it possible to decrease level of these spikes?
> 
> ### Extra information & Setup and Calibration files
> The frequency range is set to 1MHz..101MHz , 4501 points, IF BW 1.00kHz

Hi, Dmitrii1978. I have a slightly different picture in this frequency range.
![W7_64_LibreVNA_1MHz_101MHz_-10dBm_4501_1kHz_](https://github.com/jankae/LibreVNA/assets/79474615/66a5ea35-dc41-4135-822b-4d9f6afe4c21)

It is possible that I have a different LibreVNA device (six-layer board and added LO harmonic filters).
https://github.com/jankae/LibreVNA/issues/161#issuecomment-1372602939

Perhaps such filters already produce better results than yours.
Often bursts can be significantly reduced by changing one frequency limit, for example, the lower one at 250 kHz. This is my result.
![W7_64_LibreVNA_1 25MHz_101MHz_-10dBm_4501_1kHz_](https://github.com/jankae/LibreVNA/assets/79474615/1d72bd6a-8f7d-442d-b25a-ea15d99a0359)

Even changing the number of scanning points by one helps to shift the parasitic bursts in frequency.
![W7_64_LibreVNA_1 25MHz_101MHz_-10dBm_4501_20Hz](https://github.com/jankae/LibreVNA/assets/79474615/1a8ae367-9c23-4db4-ac44-027e0821c2cf)
![W7_64_LibreVNA_1 25MHz_101MHz_-10dBm_4500_20Hz](https://github.com/jankae/LibreVNA/assets/79474615/a00b7d8b-cc2d-4ac1-bca6-72751d1356ec)

But how many parasitic bursts there are even with harmonic filters of the first local oscillator, if you use scanning boundaries without a shift of 250 kHz, that is, as in the case you presented.
![W7_64_LibreVNA_1MHz_101MHz_-10dBm_4501_1kHz](https://github.com/jankae/LibreVNA/assets/79474615/b5e07ab6-c62d-4814-aa10-57ac94e10d2e)

And of course, reducing scanning points can completely eliminate parasitic bursts.
![W7_64_LibreVNA_1 25MHz_101MHz_-10dBm_450_20Hz](https://github.com/jankae/LibreVNA/assets/79474615/a04dafa1-e7ba-416a-b839-efb49d333be4)
