### ISSUE TITLE
v1.5 and later segmented sweeps don't work

### ISSUE THREAD

**Issue by crnkAWE** [jankae/LibreVNA#221]
### LibreVNA Version

LibreVNA Version (64 bit): 1.5.0-alpha.2-54de9fd6b
OS: Windows 10 Version 2009
CPU Arch: x86_64

### Steps to reproduce

- LibreVNA app is launched
- LibreVNA device is connected automatically
- Check to ensure *allow segmented sweeps* is checked in Preferences -> Acquisition
- Set starting frequency to 1 MHz and final frequency to 10 MHz
- Set number of points to 5000 
- Take measurement

### Expected behavior

I would expect the sweep to continue over the entire 9 MHz band, but it restarts halfway through, never completing the full measurement.

### Extra information & Setup and Calibration files

Using firmware version: EmbeddedFirmware-hw-rev-B-v1.5.0

**Comment by jankae** [comment]
Ah, my bad for not having proper integration tests set up. You are absolutely correct and I broke that feature a while ago. Should be fixed now and I will work on the automatic tests when I find the time for that.
