### ISSUE TITLE
Add keyboard shortcut for CSV export

### ISSUE THREAD

**Issue by theNewMKE** [jankae/LibreVNA#253]
### Summary

I would like to propose an enhancement to the graphic user interface (GUI) that allows users to export data in CSV format using a keyboard shortcut. Specifically, I'm suggesting a combination such as Control + S or another combination of your choice.

The motivation behind this feature is straightforward: shortcuts can significantly improve efficiency by reducing the number of clicks required to perform a common task. So, having a shortcut for exporting data in CSV format would save time and effort.

More importantly, I'm interested in automating data export processes using LabVIEW, which requires saving data to CSV files. Having a dedicated keyboard shortcut for CSV export would benefit this process by making it more convenient to integrate with my workflows.

I believe that adding a keyboard shortcut for CSV export would be a valuable addition to the GUI.
Please let me know if my request is reasonable and let me know if this is possible!

### Paths to implement it

![Screenshot 2024-05-21 215210](https://github.com/jankae/LibreVNA/assets/39660747/fa6d78bd-3881-41a2-8050-7bd3edbf2d0d)
As shown in the picture, a shortcut for the export button would largely benefit my work.

### Extra information

It would also be helpful if you let me know which part of the code for the GUI is related to the shortcut adding!
If you cannot focus on this task currently because of your schedule, I can, hopefully, work on it by myself and give you an update.
Since I am not an expert in C/C++, so I would like to seek help from you, including where part should I add the code to!
Thank you in advance and I am looking forward to hearing back from you!

**Comment by jankae** [comment]
closing because this is not planned at the moment and there are other methods to automatically grab the data.
