### ISSUE TITLE
SCPI Command to allow for Logarithmic Sweep

### ISSUE THREAD

**Issue by BassDave** [jankae/LibreVNA#266]
### Summary

Hi! 

is it possible to choose a LOG Sweep via SCPI? 
In the programmer's guide, no information was found! 

thank you very much! 

### Paths to implement it

provide for a SCPI command that ticks the LOG Sweep box in GUI

### Extra information

Thank you!

**Comment by jankae** [comment]
Thanks for the suggestion, the LOG command is indeed still missing in the SCPI API. Shouldn't be too difficult to add, I will do that soon

**Comment by BassDave** [comment]
Thank you very much! Could you be so kind as to update the Programmer's Guide then as well? 

Thank you very much for your support! 

Kind Regards!

**Comment by jankae** [comment]
...and done: 009de1a

Of course the programming guide is updated as well. The new command is called "VNA:SWEEPTYPE" and it allows you to switch between linear and log sweeps

**Comment by BassDave** [comment]
works great! Thank you very much!
