### ISSUE TITLE
SIUnitEdit goes blank

### ISSUE THREAD

**Issue by nbgsmk** [jankae/LibreVNA#27]
Hello! 
Just a smal notice here, nothing critical: if you click to the *left* of the most significant digit within SIUnitEdit and roll the mouse, the field goes blank. Still it seems to update (on the default 3rd digit) but the content is invisible. Only after clicking on another SIUnitEdit, or one of the docks, it becomes visible again.

**Comment by jankae** [comment]
Hi, thanks for noticing this. I believe 642995c should fix that, please check with this version to confirm: https://github.com/jankae/LibreVNA/actions/runs/759326941

**Comment by nbgsmk** [comment]
Great, works fine for me!
Closing.
