### ISSUE TITLE
Board file seems corrupt

### ISSUE THREAD

**Issue by KiranKanchi** [jankae/LibreVNA#30]
Hi,

The .brd file in hardware folder is less than 1MB which means its incomplete/corrupt. Is it supposed to be that way ?

Kind regards
Kiran Kanchi

**Comment by jankae** [comment]
Well, it is definitely not supposed to be corrupt. I just downloaded it fresh from Github and could open it without a problem (Eagle 9.3.1). Why should the file be at least 1MB?

**Comment by KiranKanchi** [comment]
Ah! I used cadence Allegro to open the .brd file.

**Comment by jankae** [comment]
Yeah, I'd be surprised if that had worked ;)
