### ISSUE TITLE
Electrical Parameter Trace Measurements Z,R,L,C etc  

### ISSUE THREAD

**Issue by GoodTesla** [jankae/LibreVNA#33]
It would be nice to have built in traces for derived values. Some Examples:
Series R,L,C Quality factor, Z, VSWR, etc.

**Comment by jankae** [comment]
I assume you want to measure these parameters by an S11 measurement? E.g. a capacitor to GND would be connected to port 1 and you would like to see its capacitance instead of the S11 value?

**Comment by jankae** [comment]
A first attempt at the feature: e27e594
You can find the compiled version here: https://github.com/jankae/LibreVNA/actions/runs/977042194

There are additional axis types available for the graphs as well as different output formats for the markers:
![image](https://user-images.githubusercontent.com/16818866/123560408-38a5dd00-d7a2-11eb-978c-2aa90cf00e16.png)

This is barely tested at all, I just wanted to provide a quick prove of concept. If you find any errors in the calculations please let me know. I will also check it more thoroughly at a later time.

**Comment by GoodTesla** [comment]
Wow that was fast! I will give this a try and let you know if I see any issues. 

Great tool! Been following this project for a while and we finally got a unit to play with in house. 

Thanks again.
