### ISSUE TITLE
New Feature Suggestion - VSWR Circle

### ISSUE THREAD

**Issue by itsaname** [jankae/LibreVNA#41]
It would be nice to have built in traces for certain vswr circle,its very useful in antenna match. Some Examples:
vswr=1.5, vswr = 2 etc.

**Comment by jankae** [comment]
As it is now, the trace module does only support traces created from the incoming measurements or from touchstone/CSV files. 
Maybe it could be easier to just add the option to display built in lines directly on the graphs? (without actually creating a trace and filling it with data).
What other built in lines/traces do you have in mind?

**Comment by itsaname** [comment]
sorry for my poor English, it would be nice to add  Q-arcs too.

**Comment by jankae** [comment]
okay, that sounds like it could just be an addition to the smithchart and should be doable. I'll probably implement that at some point, thanks for the suggestion

**Comment by jankae** [comment]
Well, it took a while but customizable circles/arc for the smith chart are now available: cd106b3. You can configure them in the Setup-Dialog of the smith chart:
![image](https://user-images.githubusercontent.com/16818866/148621286-a6c38895-4889-40f6-9a39-55e9c1b9b23b.png)
Available options are VSWR, constant resistance, constant reactance and constant Q. Here is an example how it looks like on the smith chart:
![image](https://user-images.githubusercontent.com/16818866/148621257-4f3558b1-7f46-4b75-aec5-00d6e80db390.png)
