### ISSUE TITLE
Possible to lower the minimum measurement frequency?

### ISSUE THREAD

**Issue by bwalker000** [jankae/LibreVNA#49]
I have work where it would be nice to get down closer to 50kHz than 500kHz. I suspect that would be a filter change, but I don't know about the intrinsic bandwith of the other parts of the system. Thanks for considering.

**Comment by jankae** [comment]
You can try to enter lower values in the GUI, it will accept frequencies all the way to DC. But the limitation in the hardware is the ADL5801. It is only specified down to 10MHz. Although it works reasonable well down to 100kHz, at even lower frequencies it has a lot less conversion gain which means the VNA loses dynamic range. Unfortunately, this can not be solved with a simple filter change.

For a second version of the LibreVNA, I am thinking about sampling the signal directly (without any mixers) for the very low frequencies, this would enable measurements at essentially DC (only limited by the DC blocking caps).
