### ISSUE TITLE
Idea: 3D-Printed Sheilding

### ISSUE THREAD

**Issue by BrendaEM** [jankae/LibreVNA#51]
Hi All,

I am quite interested by this project. If shielding has not yet been implemented, why not use conductive filament to 3D-Print shielding plate for the circuit.

The filament, would have to take some heat, so it would seem that conductive ABS would be better than the PLA.

Perhaps even, the 3D print could also be coated with high-copper content conductive paint, to give it just a little more RF shielding mojo.

If there is interest, perhaps I could help, I have Rhino 3D, and am pretty handy with it.

I suppose that making an open-source CNC model would help too.

Take Care,
BrendaEM

**Comment by britovski** [comment]
Hello.

Was shielding effectiveness measured using any method at all? I'm also
interested in testing some 3D-printing conductive materials for shielding,
and if we had guidelines to measure and compare it would be good to work on
it.

Em ter., 12 de out. de 2021 às 12:42, jankae ***@***.***>
escreveu:

**Comment by jankae** [comment]
The only thing I compared was the dynamic range (or rather: the signal leakage between the ports) with and without shielding. You could attempt the same thing with a 3D-printed shield and compare it to a measurement with an aluminum shield.
But I believe most of the remaining signal leakage is actually through the PCB/components and not through the shield (various attempts to improve the shielding like the RF gaskets in the picture above did not make any difference)
