### ISSUE TITLE
System dynamic range improvement

### ISSUE THREAD

**Issue by blackberryer** [jankae/LibreVNA#52]
In the end, it was only inspired by the nanovna V2 project. The dynamic range of the system can be improved by redesigning the directional bridge. The MMIC-based differential amplifier instead of the balun can reduce the cost and increase the SNR, so as to achieve a faster scanning rate. Simply use an BJT LNA, which is much cheaper than a broadband balun. 
I am here to make suggestions, not sure if it is feasible in principle.

**Comment by blackberryer** [comment]
I’m sorry for not being very clear, maybe it’s just my own guess. In fact, what I mean is that I want to make some modifications to the following circuit.
![image](https://user-images.githubusercontent.com/6220546/137126965-0730759e-eef5-4ed3-8692-a42afa918788.png)
Converted into the following scheme:
![image](https://user-images.githubusercontent.com/6220546/137129491-f2feaf0e-e3f6-410a-8053-4bb10a2f1964.png)

**Comment by zsellera** [comment]
No RF engineer here, but using such amps makes sense if:

1. want to match different impedances (buffer)
2. signal conditioning (amplification before the mixer stage)
3. single-ended to double-ended conversion, or vice-versa

Here the bridge provides a differential output, and the mixer offers a 50 ohm *differential* input, which is perfect for the bridge (as it offers the same output). The balun here may act as a filter for the common-mode component coming from the bridge (guess), but I don't know why is it needed - maybe @jankae can shed some light on it.

The nanovna v2 is a switch-porn, where the bridge's differential 50 ohm output must be matched to a single-ended 50-ohm line. The baluns seen on the original (open) v2.2 design seem to me bad design choice, probably driven by cost reasons only. Having a differential input amp there makes perfect sense.

The ADL5960 has those preamps there probably for all three reasons (impedance matching, preamp and SE to differential conversion).

**Comment by blackberryer** [comment]
> No RF engineer here, but using such amps makes sense if:
> 
> 1. want to match different impedances (buffer)
> 2. signal conditioning (amplification before the mixer stage)
> 3. single-ended to double-ended conversion, or vice-versa
> 
> Here the bridge provides a differential output, and the mixer offers a 50 ohm _differential_ input, which is perfect for the bridge (as it offers the same output). The balun here may act as a filter for the common-mode component coming from the bridge (guess), but I don't know why is it needed - maybe @jankae can shed some light on it.
> 
> The nanovna v2 is a switch-porn, where the bridge's differential 50 ohm output must be matched to a single-ended 50-ohm line. The baluns seen on the original (open) v2.2 design seem to me bad design choice, probably driven by cost reasons only. Having a differential input amp there makes perfect sense.
> 
> The ADL5960 has those preamps there probably for all three reasons (impedance matching, preamp and SE to differential conversion).

I tried this circuit, which is basically effective, but the AGC part of V2 version is not open source, resulting in the noise of more than 1G in my actual test, but the approximate track is correct. In addition, the author of V2 chose balun, which is unreasonable. He may not have seen jankae's design. If he has, the design of balun should be better

**Comment by YuryW** [comment]
An improvement in the frequency dependence of the dynamic range of S11 and S22 (at the same time as S12 and S21) can be obtained by replacing two baluns at the meter ports in LibreVNA with wider ones, for example, MABA-011108 ( https://www.macom.com/products/product-detail/MABA-011108#part-tech-order   )  .
A further increase in the dynamic range of S12 and S21, in my opinion, is achieved by continuing to apply the already used idea - to install an additional QPC6324 between the switch and the ports themselves. Then the noise floor of S21 and S12 will be determined by the bandwidth and shielding of the individual LibreVNA nodes.

**Comment by YuryW** [comment]
If we assume that the spurious signal penetrates through the paths indicated in the figure in red, 
![Spurious signal paths](https://user-images.githubusercontent.com/79474615/199678444-6f3684cc-5219-4040-8aac-48b6122873f4.jpg)
then I propose one of the solutions as follows. At the points marked in the figure, 
![Decoupling](https://user-images.githubusercontent.com/79474615/199678567-8052fa04-2da7-4a78-9e85-db33ef60c518.jpg)
as an example, put a 12dB attenuator and a TRF37A73 amplifier. S12 of such an amplifier decreases with increasing frequency and reaches -19...-21 dB at 4...6GHz. That is, if the assumption and paths of spurious signal penetration are correct, we will get an improvement in isolation between LibreVNA ports in the upper part of the range of at least 31 dB.
Or the second option is to put a separate MAX2871 synthesizer on each ADL5801 mixer.

**Comment by YuryW** [comment]
Hi Slawek.
If we assume that LO-to-RF Input Leakage = RF-to-LO Input Leakage for ADL5801, then at 5500 MHz they are equal to 29 dB. A 25 dB resistive coupler has 0 dB isolation. The simulation showed that for a TCM1-63AX+ bridge with an input resistive attenuator, the reflected wave is at best 19 dB at 6 GHz. On two QPC6324 switches, 1.35*4=5.4dB will be lost in both directions. Then we get mathematically only along this path we have an isolation between the LibreVNA ports 19+5.4+0+29+29=82.4 dB with a calibrated load on port No. 1.

**Comment by YuryW** [comment]
Good day everyone.
Assuming that the isolation in the ADL5801 LO -> RF is approximately equal to RF -> LO only at frequencies closer to 5...6 GHz, and at low frequencies RF -> LO is much less than LO-> RF, which is indicated in the datasheet approximately 29 dBc, then the problem of improving the dynamic range at high LibreVNA frequencies can still be solved by adding a 12 dB attenuator and a TRF37A73 amplifier before the LO inputs of the first mixer (see post on Nov 3, 2022 above). Indirectly, this is evidenced by the changes that the 6-layer version received and which, in my opinion, led to an improvement in the dynamic range compared to the previous version - namely, in the 6-layer version, a 10 dB attenuator appeared before the LO ADL5801 input (except Port 2) .

![Isolation](https://user-images.githubusercontent.com/79474615/211549521-bacf004a-b4fc-4928-96ad-fd1a12df6d6a.jpg)
![Isolation_1](https://user-images.githubusercontent.com/79474615/211549593-801f9586-0ea4-495c-9d3b-4c55642f5f37.jpg)

In the absence of a signal at the RF input of the ADL5801, it is probably enough to have the first local oscillator signal at the LO input ADL5801 and the HF Source signal reduced by about 70 dB to get an IF of about -70 dB at the mixer output.

![Isolation_2](https://user-images.githubusercontent.com/79474615/211550735-bf9c8c99-0753-453f-8d5f-8268c692a085.jpg)

**_And perhaps it is enough to put a chain of 12 dB attenuator and TRF37A73 amplifier just before the LO input of the ADL5801 reference receiver. And for Port 1 and Port 2, before the LO input of the ADL5801, install only 10 dB attenuators._** 
Moreover, the frequency response of the dynamic range in the formula 25 + 29 (frequency) +10 +10 will determine the value of 29 dB in the current LibreVNA scheme, which will change quite strongly when the frequency changes up to 65 dB at low frequencies.
Best regards.

**Comment by YuryW** [comment]
A little continuation. I do not have a 3D electromagnetic simulator, but in my opinion in the layout of the 6-layer LibreVNA printed circuit board there are several dangerous approaches (from the point of view of mutual interference through vias less than necessary at -100 dB) of the 1.Lo and HF Suorce signal lines. Points 1 and 4 are especially questionable. In my opinion, there are no restrictions to remove these lines with signals from each other (at points 1, 2, 3, 4) to the maximum possible distance in this case without changing the dimensions of the case.

![Isolation_3](https://user-images.githubusercontent.com/79474615/211823257-f66bf0a0-83d2-435e-baa9-34034de5586f.jpg)
![Isolation_4](https://user-images.githubusercontent.com/79474615/211823310-052c9874-948a-47cf-a61c-9ad3a89869c3.jpg)

To view the traditional gerber and exellon files, I used the wonderful program for CNC machine tools (manufacturing of simple printed circuit boards) GGEasy.

https://github.com/XRay3D/GERBER_X3/releases 

Best regards.
