### ISSUE TITLE
Implement outlier removal, in addition to averaging?

### ISSUE THREAD

**Issue by bwalker000** [jankae/LibreVNA#53]
At low frequencies the errors in impedance measurements seems less like smoothly distributed noise, and more like spike noise. Averaging helps to reduce these measurement errors, but only so far. My instinct is that if the code removed outliers then the results at low frequency would be dramatically cleaner. I've attached a screen shot demonstrating the issue that I'm referring to.

It might be as simple as taking N measurements and removing the two highest and two lowest data points. My suspicion is that would clean things up dramatically.

The attached figure is showing R + j*X as a function of frequency.

![Screen Shot 2021-10-13 at 11 48 15 AM](https://user-images.githubusercontent.com/76655013/137170309-c4053c23-4370-49cf-8dea-726080f5f359.png)

**Comment by bwalker000** [comment]
This is very helpful. It definitely reduces the problem.

I'm not convinced however that a median filter across acquisitions would be worthless. As I watch the traces I see that the spikes stay at the same frequency, but their amplitude is definitely changing.

Of course you could do a median filter across acquisition number and frequency. Two dimensional median filter.

**Comment by jankae** [comment]
I suppose it could be helpful to change the behavior of the averaging filter (across acquisition number). Maybe give the user the choice between median and mean? This should be fairly easy to implement.

**Comment by jankae** [comment]
I just added an option to select the behavior of the averaging filter: dced173
There are two choices available: mean (same behavior as before) and median (across acquisitions, not across samples). The selection can be done in Preferences->Acquisition:
![image](https://user-images.githubusercontent.com/16818866/144314779-c14ddaee-97df-40ad-b5d4-8a1977e10619.png)
