### ISSUE TITLE
gui/traces: highlight traces name and markers in plots throughout color boxes

### ISSUE THREAD

**Issue by sophiekovalevsky** [jankae/LibreVNA#56]
I've been cooking this idea and I think would be really great if we can integrate it into the gui. 

Basically instead of showing colored traces name and marker in plots, I guess one neat visual mode is wrap it within a rectangle. Something like this: 
![image](https://user-images.githubusercontent.com/1287883/137601706-2df3bddc-7cd6-4d5e-bf98-b453dca5f364.png)

What I'm not really sure about if whether to add this same approach for traces dock or if it's too overwhelming. Suggestions are super welcome.

**Comment by jankae** [comment]
Nice idea, I like it (especially with the rounded rectangles in your screenshot)! For the traces dock, I would prefer to leave it as it is for now :)
One caveat when implementing this: depending on the trace color, the font might be difficult to read (with very dark traces). For the markers (the triangle in the plots), the font is either displayed in black or white, depending on the brightness of the trace (and triangle) color. I am not sure whether the current implementation of that is perfect, but something like this should probably added for this feature as well.

Do you want to take this on or should I try my best to implement it?

**Comment by sophiekovalevsky** [comment]
@jankae, I guess we can fix the background issue if instead of showing a transparent font, we set the color to white. 

I'm more than happy to implement this =)
