### ISSUE TITLE
FPGA Build

### ISSUE THREAD

**Issue by djfarrell** [jankae/LibreVNA#68]
Trying a build of the FPGA source.  ISE 14.7 on Ubuntu 18.   Rebuilding cores fails with the PLL core  https://wiki.archlinux.org/title/Xilinx_ISE_WebPACK had the solution linking to JAVA6. Affter the fix, build succeeds. Something may be wrong, the Clocking wizard indicates input clock of 16MHz and CLK_OUT1 output of  102.4MHz.  Elsewhere I see the design indicates a 160MHz clock.  What should the FPGA clock be?

**Comment by jankae** [comment]
102.4MHz is correct. At a very early stage, I had the FPGA running at 160MHz and forgot to adjust the name of the clock signal. I have changed that now.

**Comment by djfarrell** [comment]
Thanks
