### ISSUE TITLE
New feature suggestion

### ISSUE THREAD

**Issue by Chorbu** [jankae/LibreVNA#73]
Hello all,

May is it possible to add an option in Preferences / graphs to increase or decrease the thickness of traces ?
and add a button in calibrations measurements to erase all calibrations in only one action ?
May is it possible when adding a marker in S21 trace for example that others automatically set in the smith chart or other traces ?

Best regards to all
Thank you in advance Patrick F5SUE

**Comment by jankae** [comment]
Hi Patrick,
> May is it possible to add an option in Preferences / graphs to increase or decrease the thickness of traces ?

Yes, possible and added now:
![image](https://user-images.githubusercontent.com/16818866/144756757-3eda1d70-fa13-49ed-a78c-458d12ac8ee5.png)

> and add a button in calibrations measurements to erase all calibrations in only one action ?

You can already select multiple measurements at the same time (using Ctrl/Shift) to measure them at the same time (obviously only possible if they do not require conflicting calibration standards). With the latest commit, you can now also delete all selected measurements at once.

> May is it possible when adding a marker in S21 trace for example that others automatically set in the smith chart or other traces ?

This is a tricky one. Markers are linked to one trace, not a set of traces. This has been discussed before and while it does impose some restrictions, it also provides a huge flexibility when importing new traces or deleting some. I assume you want to use the markers to read out the values of all traces at a specific frequency? What you can do at the moment is this:
1. Create a marker for every trace that you want one one (e.g. for S11, S12, S21 and S22 with the default traces). Each individual marker will show up in its graph:
![image](https://user-images.githubusercontent.com/16818866/144757063-6a481e6f-8471-42d2-86f2-e155aa52245e.png)
2. Link the created markers by selecting them in the marker dock and right-clicking:
![image](https://user-images.githubusercontent.com/16818866/144757121-50d7aa5d-d8cd-4a52-8a30-9f3f2409ce9e.png)
3. The additional number in the marker dock identifies the linked markers (you can have multiple non-overlapping groups of linked markers):
![image](https://user-images.githubusercontent.com/16818866/144757160-a13df0c9-eb7c-4973-a7e3-fdc354d90e76.png)
4. Moving one marker also moves all others now.

It might be possible to create a shortcut for these steps (e.g. a button "create a marker for all traces and link all of them"). I am not sure where/how that should be implemented in the GUI. If someone has any suggestions about that please share them.

One small remark for the future: Please open separate issues for every improvement request. It might seem easier to simply write them into one issue (especially if they are small requests like these), but keeping track of them is a lot harder if different stuff is combined. Thanks :)

**Comment by Chorbu** [comment]
Hi Jan,

Thank you so much for mods on your software ! i'm so happy to use your VNA !
I follow mods and discussions all days. Thanks for the community to share your fantastic project.
Specifications are under all other low cost VNA's i had used. (excuse me for my english...)

Here is my website : http://rflab.fr/

Best 73's Patrick

**Comment by jankae** [comment]
Thanks, I am happy to hear that :)

I thought some more about the shortcut to create linked markers and I believe an additional button might do:
![image](https://user-images.githubusercontent.com/16818866/144758868-28656626-3f08-41a0-96c2-a8525a8d029e.png)
Clicking this button creates a marker for every trace and links them. It gets you the exact same result as the four steps I explained above but with a single click.

**Comment by Chorbu** [comment]
Superb Jan,

Thank you !

Best 73's Patrick
