### ISSUE TITLE
Ability To Change Scale Of Smith Chart Display

### ISSUE THREAD

**Issue by dsbrantjr** [jankae/LibreVNA#77]
When looking at either high return loss devices or conversely those with negative resistance/reflection gain characteristics which would plot outside of the edge of a normal Smith chart, the ability to expand or contract the scale of the chart display about the center would be helpful.  I would suggest that the user input would be to specify the reflection coefficient at the edge of the chart, normally 1.   This might tie in with the request for plotting VSWR or Q circles.

As an aside, Philip Smith's firm Analog Instruments, (he would answer the phone himself) used to sell expanded- and greatly-expanded center charts. He or someone else sold expanded low-impedance charts too, useful for RF power transistor matching design, and negative resistance charts for oscillator and paramp design.  I do not think there would be much demand for this type any more, however.

**Comment by jankae** [comment]
I started implementing this, so far a basic zoom feature for the smith chart is available in the setup dialog:
![image](https://user-images.githubusercontent.com/16818866/147858420-c5583d36-1e7f-43a0-bfcc-83085cfd501a.png)
The scale can either be set by the zoom factor or the reflection coefficient at the edge (these two settings are inversely proportional to each other). You can also use the scroll wheel on the smith chart directly to zoom (no need for the setup dialog in this case).
Example with magnified smith chart:
![image](https://user-images.githubusercontent.com/16818866/147858499-220b5bcf-1ca9-419d-920e-8db9ceebf551.png)
