### ISSUE TITLE
Discrete (Measurement Points Only) or Interpolated (Freely Movable) Markers

### ISSUE THREAD

**Issue by dsbrantjr** [jankae/LibreVNA#81]
It would be useful/convenient to be able to choose between discrete or Interpolated frequency markers.  I have noticed that it is disconcerting for some users to key in a frequency and have the marker jump to a nearby measurement point rather than the requested frequency.  Others prefer to have the marker step between discrete measurement points.

**Comment by jankae** [comment]
... and done: 2f7449e
It has to be enabled in the preferences first:
![image](https://user-images.githubusercontent.com/16818866/148538829-d8e3a64d-d09d-428a-a0e9-2ce7da6d2a88.png)
