### ISSUE TITLE
SOLT, Setup & Cal-Kit Files

### ISSUE THREAD

**Issue by dna35** [jankae/LibreVNA#84]
Requesting to have the SOLT file displayed at the bottom of the GUI. With many different SOLT files, it may not be known which one is in use. If there is sufficient room the request would be in this order:

1- Add SOLT file in-use to bottom of GUI
2- Add Setup file in-use to bottom of GUI
3- Add Cal-Kit file in-use to bottom of GUI

**Comment by jankae** [comment]
The calibration label in the toolbar has a mouseover-Text that can show you the filename (hover the mouse over it for a second or two):
![image](https://user-images.githubusercontent.com/16818866/150603142-7a34778b-ba08-4f53-bbe6-45d66ae6d1ab.png)
I have also added some information in the statusbar now:
![image](https://user-images.githubusercontent.com/16818866/150603173-4d4554c9-0c26-4983-9b5d-881532e59266.png)
The setup file and calibration (when in VNA mode) are displayed. The Calkit name is not available in any variable at the moment (but is normally identical to the calibration file name).
