### ISSUE TITLE
Feature request: load setup and calibration files from command line argument

### ISSUE THREAD

**Issue by CGrassin** [jankae/LibreVNA#88]
A command line argument to be able to immediately load a setup file upon launch would be very useful.
Another command line argument to load a calibration file would also be a great addition.

**Comment by jankae** [comment]
Thank you for the suggestion, I have now added two new command line parameters:
![image](https://user-images.githubusercontent.com/16818866/156161925-a3daecd2-725d-42f5-ad5c-63c2c4722f49.png)
