### ISSUE TITLE
Add the possibility of entering EMI/EMC standard limit for Spektrum Analyser

### ISSUE THREAD

**Issue by HadesDT** [jankae/LibreVNA#96]
Hi,

One proposal of improvment on the Spektrum side.

- Add the possibility of entering EMI/EMC standard limit values to set, for example, a CE102 limit and see if the setup passes the EMI/EMC standard. As on the Spektrum R&S, see print screen

![rs](https://user-images.githubusercontent.com/4487204/160543159-fd8dad7c-fc4b-4254-9289-e9f8651fe126.png)
![rs2](https://user-images.githubusercontent.com/4487204/160543166-c18022e4-e931-444b-b347-2c413cd9f5cf.png)

Cheers,

**Comment by sp9bsl** [comment]
Hi,
I would adwice some caution using LibreVNA as spectrum analyzer, especially for EMI/EMC measurements. Jan mentioned the way SA mode works in LibreVNA, it just remove some of the aliases during measurements. Another thing, for EMC measurements you need specyfic time for averaging and of course CISPR filter shape. LibreVNA is the best thing for network measurements, not for SA application. I use daily R&S stuff like ESR, ESL with GTEM/TEM and LISN. Our great little thing is not very usable for such measurements and may do some confusion reading the results...

**Comment by HadesDT** [comment]
Hello,
I'm in phase with your comment.
It's just a proposal to add limit manually to pre-test some setup. Of course for the real test in EMI/EMC room we use real labo equipment.

**Comment by jankae** [comment]
Hi,
although I agree that the LibreVNA probably is not accurate enough or does not have the correct filter for good EMI/EMC measurements, I think limit checking is a worthwhile feature and implemented it:
![LimitTest](https://user-images.githubusercontent.com/16818866/164709416-3e42db3a-07a5-48ee-8711-dc0d4224bae9.png)
Setting it up works like this:

- Configure constant lines in a XY-plot (right-click->setup)
- Set the constant line points according to your limit and select whether this is a max or min threshold (high limit or low limit)
- You can choose the pass/fail indicator behavior under window->preferences->graphs->limit checking

Here is also the setup file of the example from my screenshot:
[limit.zip](https://github.com/jankae/LibreVNA/files/8540683/limit.zip)

The pass/fail result is also exposed via the SCPI API, however the actual configuration of the limits must be done in the GUI (not possible via SCPI).

**Comment by HadesDT** [comment]
Hello,

I try this version and works perfectly ! Thx for your job !

**Comment by jankae** [comment]
Thank you for confirming that it works like this for you :)
