### ISSUE TITLE
TDR seems to calculate wrongly

### ISSUE THREAD

**Issue by dotmjsc** [jankae/LibreVNA#97]
Look at the attached picture.
Open is displayed as short, short as open and 75R as ~35R. Seems to be a minor calculation error (or I do not get how to configure this?)
Thank you.
M.
![LibreVNA_bug](https://user-images.githubusercontent.com/59560734/161437269-628d03e1-2db6-4abc-8d16-364fc201cae8.png)

**Comment by jankae** [comment]
Hi, it is possible to configure the TDR wrong but I can't tell just by the screenshots. Can you please provide the setup file (File->Save Setup) and also a touchstone file with your S parameter data? That way I should be able to replicate your calculations for the TDR.
TDR seems to work here after a quick test (30cm coax terminated with a short):
![image](https://user-images.githubusercontent.com/16818866/161438308-b5b72240-56d7-4ee1-9fdc-c9c9d8bed764.png)

**Comment by dotmjsc** [comment]
Wow, fast answer! Thanks.
Here is the desired data for 30cm with sma short.
[TDR_bug.zip](https://github.com/jankae/LibreVNA/files/8405094/TDR_bug.zip)

**Comment by jankae** [comment]
Your setup looks correct. However, your S11 data is approximately "open" (reflection coefficient +1) at its lowest frequency (1 MHz). This is the reason why your TDR shows it as an open as well.

From your data I can't tell why your S11 is measured that way. This could have happened if the short and open standards were mistakenly swapped during the calibration. Can you repeat your calibration and measurement please? In any case, this points to an error/bug in the S11 acquisition. Any subsequent TDR calculations seem correct to me.

**Comment by dotmjsc** [comment]
I never did a calibration after receiving the unit. Will repeat it right now and try again!

**Comment by dotmjsc** [comment]
Ok, That was it, thank you! After doing the calibration the trace looks exactly the same as yours.
